# This file was generated by GoReleaser. DO NOT EDIT.
cask "fpp2" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/devinjeon/FastPathPicker/releases/download/v#{version}/fpp2_v#{version}_darwin_amd64.tar.gz"
      sha256 "f354255594989a7b11a14d3e441cd77f686b0ffd2d85420d556e592bf4d9d652"
    end
    on_arm do
      url "https://github.com/devinjeon/FastPathPicker/releases/download/v#{version}/fpp2_v#{version}_darwin_arm64.tar.gz"
      sha256 "976deaff1686abae476dd40bc2b87c47fc7fde12cb4f661d9b01c5eb63fe73b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devinjeon/FastPathPicker/releases/download/v#{version}/fpp2_v#{version}_linux_amd64.tar.gz"
      sha256 "641b4fad7c35f2bc47dc6fa2e974e2a62cf84e08220825da92836f02ee39bd0c"
    end
    on_arm do
      url "https://github.com/devinjeon/FastPathPicker/releases/download/v#{version}/fpp2_v#{version}_linux_arm64.tar.gz"
      sha256 "bd818f35076fb0d50a52a16cec9caa7d64dca40f00fca96ef3e96b5ecdad1704"
    end
  end

  name "fpp2"
  desc "Fast PathPicker — a high-performance Rust drop-in replacement for Facebook's PathPicker"
  homepage "https://github.com/devinjeon/FastPathPicker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fpp2"

  # No zap stanza required

end
